- name: create output folder
  file:
    name: "out"
    state: directory

- name: create CA private key 
  openssl_privatekey:
    path: "./out/CA.pem"    
    passphrase: "{{ secretfraze }}" 
    cipher: aes256   

- name: create CA CSR
  openssl_csr:
    path: ./out/CA.csr
    privatekey_path: ./out/CA.pem
    privatekey_passphrase: "{{ secretfraze }}"
    common_name: "Local Intermediate CA"
    country_name: BY
    organization_name: EPAM
    email_address: test@test.com
    
- name: create CA certificate
  openssl_certificate:
    path: ./out/CA.crt
    csr_path: ./out/CA.csr
    provider: selfsigned
    privatekey_path: ./out/CA.pem
    privatekey_passphrase: "{{ secretfraze }}"                  
    
        

   
