- name: lookup git
  hosts: localhost

  vars_prompt:

    - name: username
      prompt: "Enter your git username"
      private: no

    - name: password
      prompt: "Enter your password"
      private: yes

  tasks:
  - debug:
      msg : "{{ lookup('lookup_git', username, password) }} "
