- name : Practise with openssl module  
  vars:
    names:
      - 'www.example.com'
      - 'customer.example.com'
      - '*.datastore.example.com'

  hosts: localhost

  tasks:

    - name: create CA private key 
      openssl_privatekey:
        path: ./CA.pem    
        passphrase: "{{secretfraze}}" 
        cipher: aes256

    - name: create CA CSR
      openssl_csr:
        path: ./CA.csr
        privatekey_path: ./CA.pem
        privatekey_passphrase: "{{secretfraze}}"
        common_name: "Local Intermediate CA"
        country_name: BY
        organization_name: EPAM
        email_address: test@test.com

    - name: create CA certificate
      openssl_certificate:
        path: ./CA.crt
        csr_path: ./CA.csr
        provider: selfsigned
        privatekey_path: ./CA.pem
        privatekey_passphrase: "{{secretfraze}}"      

    - name: create CSRs
      openssl_csr:
        path: "./{{item}}.csr"
        privatekey_path: ./CA.pem
        privatekey_passphrase : "{{secretfraze}}"
        common_name: "{{item}}"
      with_items:
        - "{{ names | replace('*','all') }}"

    - name: sign certificates
      shell: "openssl x509 -req -in ./{{item}}.csr -CA ./CA.crt -CAkey ./CA.pem -CAcreateserial -out ./{{item}}.crt -days 365 -passin pass:{{secretfraze}}"
      with_items:
        - "{{ names | replace('*','all') }}"


         

   
