- name: get the names of sites
  include_vars:
    file: sites_names
    name: names

- name: create dir for configs and mount
  file:
    path: "{{path_to_nginx_confs}}"
    state: directory

- name: generate configs for sites
  template:  
     src: vhost.j2
     dest: "conf/{{item}}.conf" 
  with_items:
     "{{ names }}"
  
- name: run docker with nginx
  vars:
    volumes:
      - "{{path_to_certs}}:/crt"
      - "{{path_to_nginx_confs}}:/etc/nginx/conf.d"
  docker:
    name: nginx
    image: nginx
    state: started
    net: "host"
    volumes: "{{ volumes }}"
  become: true
  become_method: sudo
  
