- name: Create dir for Job
  file:
    path: "{{jenkins_home}}/jobs/{{jenkins_job_name}}"
    state: directory
    owner: jenkins
  become: true
  become_user: jenkins

- name: Copy job template
  template:
     src: job_conf.j2
     dest: "{{jenkins_home}}/jobs/{{jenkins_job_name}}/config.xml"  
     owner: jenkins
  become: true
  become_user: jenkins

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  become: true
  become_method: sudo

- name: wait until jenkins is up
  wait_for:
    host: "{{jenkins_host}}"
    port: "{{jenkins_port"
    delay: 30 

- name: get a crumb for jenkins remote
  uri:
    url: "http://{{jenkins_admin_user}}:{{token}}@{{jenkins_host}}:{{jenkins_port}}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
    force_basic_auth: yes 
    return_content: yes
  register: crumb

- name: "execute job {{jenkins_job_name}}"
  vars:
### uri module takes only dicts for headers, so we must convert {{crumb}} to dict
    crumb_dict:
       Jenkins-Crumb: "{{crumb.content[14:]}}" 
  uri: 
    url: "http://{{jenkins_admin_user}}:{{token}}@{{jenkins_host}}:{{jenkins_port}}/job/{{jenkins_job_name}}/build"
    method: POST
    force_basic_auth: yes
    status_code: 201
    headers: "{{crumb_dict}}"

